version: "3.4"

volumes:
  mapa_celulas-redis:
  mapa_celulas-postgresql:

services:
  redis:
    image: redis:4.0.10-alpine
    ports:
      - "6379:6379"
    volumes:
      - mapa_celulas-redis:/data

  postgresql:
    image: postgres:11.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=mapa_celulas_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - mapa_celulas-postgresql:/var/lib/postgresql/data
